name: Auto Merge Hotfix to Other Branches

on:
  pull_request:
    types: [closed] # PR이 종료되었을 때만 실행 (머지된 경우)
    branches:
      - "release"
      - "main"

jobs:
  auto-merge:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'hotfix')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Remote update Git
        run: |
          git remote update

      # - name: Merge to develop
      #   run: |
      #     git checkout develop
      #     git merge --no-ff ${{ github.event.pull_request.head.ref }}
      #     git push origin develop

      - name: Merge to stage
        run: |
          git checkout stage
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin stage
