name: Auto Create PR for Hotfix Branches

on:
  push:
    branches:
      - hotfix/*

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Hotfix Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "main"
          branch: ${{ github.ref }}
          title: "✨ hotfix : ${{ github.ref_name  }}"
          body: |
            ## Why need this PR?
            - Figma 링크
            - Jira 이슈

            작업 내용의 개요를 작성해 주세요.

            ## Changes
            ${{ github.ref_name }} 브랜치에서 작업한 내용들을 작성해 주세요.

            ## Check List
            - [ ] 체크리스트 작성해 주세요.
          draft: true
          delete-branch: true
          labels: |
            fix
            wip
